# Generated by Django 4.2.2 on 2023-06-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
